#! /usr/bin/env python
import os
import rospy
from visualization_msgs.msg import MarkerArray,Marker
#Импорт библиотек

#Создаем ноду
rospy.init_node('rviz_markers')

#Создаем топик, в который будут публиковаться маркеры
marker_pub1 = rospy.Publisher("/visualization_pojar&postr", MarkerArray, queue_size = 2)
marker_pub2 = rospy.Publisher("/visualization_walls", MarkerArray, queue_size = 2)

#Создаем MarkerArray для вывода стен
markerArray = MarkerArray()

#Отмечаем стены по координатам начала и конца
def Mark(x,y,z,lx,ly,lz,id,r,g,b,type):
    marker = Marker()
    marker.header.frame_id = "aruco_map"
    marker.header.stamp = rospy.Time.now()
    marker.type = type
    marker.id = id
    #Задаем размеры стены
    marker.scale.x = lx+0.01
    marker.scale.y = ly+0.01
    marker.scale.z = lz+0.01
    #Задаем цвет стены
    marker.color.r = r
    marker.color.g = g
    marker.color.b = b
    marker.color.a = 1.0
    #Задаем координаты центра стены
    marker.pose.position.x = x
    marker.pose.position.y = y
    marker.pose.position.z = z
    #Задаем поворот стены
    marker.pose.orientation.x = 0.0
    marker.pose.orientation.y = 0.0
    marker.pose.orientation.z = 0.0
    marker.pose.orientation.w = 1.0
    return marker

#Добавляем стены в массив маркеров



while not rospy.is_shutdown():
  #Публикум массив маркеров в топик
  os.system('clear')
  markerArray.markers.clear()
  for i in range():
    markerArray.markers.append(Mark(1,0,0,0.1,0.1,0.1,len(markerArray.markers),1,1,0,2)) #желтый
  for j in range():
    markerArray.markers.append(Mark(1,1,0,0.1,0.1,0.1,len(markerArray.markers),0,0,1,2)) #синий
  #принт резов
  
  marker_pub.publish(markerArray)
  
  print(rospy.Time.now())
  rospy.rostime.wallsleep(0.1)
